// This file will be auto-generated by `supabase gen types typescript` once Supabase is running.
// For now, we define the types manually based on the migration files.

export type Json = string | number | boolean | null | { [key: string]: Json | undefined } | Json[]

export interface Database {
  public: {
    Tables: {
      companies: {
        Row: {
          id: string
          name: string
          logo_url: string | null
          contact_email: string | null
          phone: string | null
          plan: string | null
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          name: string
          logo_url?: string | null
          contact_email?: string | null
          phone?: string | null
          plan?: string | null
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          name?: string
          logo_url?: string | null
          contact_email?: string | null
          phone?: string | null
          plan?: string | null
          updated_at?: string
        }
      }
      stores: {
        Row: {
          id: string
          company_id: string
          name: string
          slug: string
          address: string | null
          phone: string | null
          business_hours: Json
          description: string | null
          image_url: string | null
          business_type_id: string | null
          is_active: boolean
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          company_id: string
          name: string
          slug: string
          address?: string | null
          phone?: string | null
          business_hours?: Json
          description?: string | null
          image_url?: string | null
          business_type_id?: string | null
          is_active?: boolean
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          company_id?: string
          name?: string
          slug?: string
          address?: string | null
          phone?: string | null
          business_hours?: Json
          description?: string | null
          image_url?: string | null
          business_type_id?: string | null
          is_active?: boolean
          updated_at?: string
        }
      }
      staff: {
        Row: {
          id: string
          user_id: string
          store_id: string
          company_id: string
          display_name: string
          role: string
          bio: string | null
          photo_url: string | null
          specialties: string[]
          position: string | null
          sort_order: number
          is_active: boolean
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          user_id: string
          store_id: string
          company_id: string
          display_name: string
          role: string
          bio?: string | null
          photo_url?: string | null
          specialties?: string[]
          position?: string | null
          sort_order?: number
          is_active?: boolean
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          user_id?: string
          store_id?: string
          company_id?: string
          display_name?: string
          role?: string
          bio?: string | null
          photo_url?: string | null
          specialties?: string[]
          position?: string | null
          sort_order?: number
          is_active?: boolean
          updated_at?: string
        }
      }
      menus: {
        Row: {
          id: string
          store_id: string
          company_id: string
          name: string
          category: string | null
          description: string | null
          price: number
          duration_min: number
          image_url: string | null
          is_public: boolean
          sort_order: number
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          store_id: string
          company_id: string
          name: string
          category?: string | null
          description?: string | null
          price: number
          duration_min: number
          image_url?: string | null
          is_public?: boolean
          sort_order?: number
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          store_id?: string
          company_id?: string
          name?: string
          category?: string | null
          description?: string | null
          price?: number
          duration_min?: number
          image_url?: string | null
          is_public?: boolean
          sort_order?: number
          updated_at?: string
        }
      }
      customers: {
        Row: {
          id: string
          company_id: string
          name: string
          name_kana: string | null
          phone: string | null
          email: string | null
          line_id: string | null
          gender: string | null
          birthday: string | null
          notes: string | null
          first_visit_at: string | null
          last_visit_at: string | null
          visit_count: number
          source: string | null
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          company_id: string
          name: string
          name_kana?: string | null
          phone?: string | null
          email?: string | null
          line_id?: string | null
          gender?: string | null
          birthday?: string | null
          notes?: string | null
          first_visit_at?: string | null
          last_visit_at?: string | null
          visit_count?: number
          source?: string | null
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          company_id?: string
          name?: string
          name_kana?: string | null
          phone?: string | null
          email?: string | null
          line_id?: string | null
          gender?: string | null
          birthday?: string | null
          notes?: string | null
          first_visit_at?: string | null
          last_visit_at?: string | null
          visit_count?: number
          source?: string | null
          updated_at?: string
        }
      }
      reservations: {
        Row: {
          id: string
          store_id: string
          company_id: string
          staff_id: string
          customer_id: string | null
          menu_id: string
          start_at: string
          end_at: string
          status: string
          source: string | null
          guest_name: string | null
          guest_phone: string | null
          guest_email: string | null
          notes: string | null
          cancelled_at: string | null
          cancel_reason: string | null
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          store_id: string
          company_id: string
          staff_id: string
          customer_id?: string | null
          menu_id: string
          start_at: string
          end_at: string
          status?: string
          source?: string | null
          guest_name?: string | null
          guest_phone?: string | null
          guest_email?: string | null
          notes?: string | null
          cancelled_at?: string | null
          cancel_reason?: string | null
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          store_id?: string
          company_id?: string
          staff_id?: string
          customer_id?: string | null
          menu_id?: string
          start_at?: string
          end_at?: string
          status?: string
          source?: string | null
          guest_name?: string | null
          guest_phone?: string | null
          guest_email?: string | null
          notes?: string | null
          cancelled_at?: string | null
          cancel_reason?: string | null
          updated_at?: string
        }
      }
      shifts: {
        Row: {
          id: string
          staff_id: string
          store_id: string
          company_id: string
          date: string
          start_time: string
          end_time: string
          break_start: string | null
          break_end: string | null
          status: string | null
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          staff_id: string
          store_id: string
          company_id: string
          date: string
          start_time: string
          end_time: string
          break_start?: string | null
          break_end?: string | null
          status?: string | null
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          staff_id?: string
          store_id?: string
          company_id?: string
          date?: string
          start_time?: string
          end_time?: string
          break_start?: string | null
          break_end?: string | null
          status?: string | null
          updated_at?: string
        }
      }
    }
    Functions: {
      create_guest_reservation: {
        Args: {
          p_store_id: string
          p_staff_id: string
          p_menu_id: string
          p_start_at: string
          p_guest_name: string
          p_guest_phone: string
          p_guest_email?: string
          p_notes?: string
        }
        Returns: Json
      }
      get_available_slots: {
        Args: {
          p_store_id: string
          p_date: string
          p_menu_id: string
          p_staff_id?: string
        }
        Returns: Json
      }
    }
    Enums: Record<string, never>
  }
}
